export type Input = { symbol: string; market: string; side: 'buy' | 'sell'; executedAt: string; price: string; quantity: string; reason: string; notes: string };
export type Result = { id: string; decisionId: string; status: string; input: Input; summary: string; ante: string[]; post: string[]; raw: any };
export type SessionDecision = { id: string; symbol: string; name?: string | null; market: string; action: 'buy' | 'sell'; executedAt: string | null; executedAtText?: string; timePrecision?: 'exact' | 'approximate' | 'unknown'; price: number | null; quantity: number | null; quantityShares?: number | null; quantityText?: string | null; confidence?: number; needsConfirmation?: string[]; reason: string; notes: string; reviewId: string | null; confirmed: boolean };
export type SessionMessage = { id: string; sessionId: string; userId: string; role: 'user' | 'assistant' | 'status' | 'error'; content: string; createdAt: string; state?: 'accepted' | 'extracting' | 'needs_input' | 'failed' | 'completed' | 'cancelled'; errorMessage?: string | null };
export type ActivityEvent = { id: string; type: 'lifecycle_status' | 'reasoning_summary' | 'tool_started' | 'tool_updated' | 'tool_completed' | 'evidence_retrieved' | 'terminal_status'; label: string; purpose?: string; status: 'active' | 'completed' | 'degraded' | 'error' | 'cancelled'; provider?: string; sourceCount?: number; startedAt?: string; completedAt?: string };
export type LearningMemory = { id: string; text: string; kind: string; sourceSessionId: string; sourceDecisionId: string | null; strength: number; active: boolean };
export type SessionSnapshot = { session: { id: string; title: string; scope: string; status: string }; decisions: SessionDecision[]; messages: SessionMessage[]; memories: LearningMemory[]; activities?: ActivityEvent[]; results: Array<{ decisionId: string; reviewId: string; status: string; result: any }> };
const apiBase = import.meta.env.VITE_API_BASE_URL as string | undefined;
const unavailable = '当前未配置可用的大模型服务，请联系管理员。';
async function request(path: string, init: RequestInit = {}) { if (!apiBase) throw new Error(unavailable); const response = await fetch(`${apiBase}${path}`, { ...init, credentials: 'include', headers: { 'content-type': 'application/json', ...(init.headers || {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.message || unavailable); return body; }
export const reviewApi = {
  async listSessions() { if (!apiBase) return []; const body = await request('/sessions'); return body.sessions as Array<{ id: string; title: string; status: string; updatedAt: string }>; },
  async getSession(id: string): Promise<SessionSnapshot> { return request(`/sessions/${encodeURIComponent(id)}`); },
  async createSession(message: string, signal?: AbortSignal) { return request('/sessions', { method: 'POST', signal, body: JSON.stringify({ message, clientNow: new Date().toISOString(), timezone: Intl.DateTimeFormat().resolvedOptions().timeZone }) }) as Promise<{ sessionId: string; status?: string; warning?: string; decisions: SessionDecision[]; messages: SessionMessage[]; memories: LearningMemory[]; activities?: ActivityEvent[] }> },
  async confirm(sessionId: string) { return request(`/sessions/${encodeURIComponent(sessionId)}/confirm`, { method: 'POST' }); },
  async updateDecision(sessionId: string, decisionId: string, patch: Partial<SessionDecision>) { await request(`/sessions/${encodeURIComponent(sessionId)}/decisions/${encodeURIComponent(decisionId)}`, { method: 'PATCH', body: JSON.stringify(patch) }); },
  async sendMessage(sessionId: string, content: string, signal?: AbortSignal): Promise<SessionMessage> { const body = await request(`/sessions/${encodeURIComponent(sessionId)}/messages`, { method: 'POST', body: JSON.stringify({ content }), signal }); return body.message; },
  async updateMessage(sessionId: string, messageId: string, content: string) { return request(`/sessions/${encodeURIComponent(sessionId)}/messages/${encodeURIComponent(messageId)}`, { method: 'PATCH', body: JSON.stringify({ content }) }); },
  async deleteMessage(sessionId: string, messageId: string) { return request(`/sessions/${encodeURIComponent(sessionId)}/messages/${encodeURIComponent(messageId)}`, { method: 'DELETE' }); },
  async cancel(sessionId: string) { return request(`/sessions/${encodeURIComponent(sessionId)}/cancel`, { method: 'POST' }); },
  async waitForSession(sessionId: string, onSnapshot: (snapshot: SessionSnapshot) => void) { for (let attempt = 0; attempt < 180; attempt += 1) { const snapshot = await this.getSession(sessionId); onSnapshot(snapshot); const linked = snapshot.decisions.filter((d) => d.reviewId); if (linked.length && linked.every((d) => snapshot.results.some((r) => r.decisionId === d.id && r.result))) return snapshot; await new Promise((resolve) => setTimeout(resolve, 500)); } throw new Error('复盘等待超时，请稍后查看服务状态。'); },
};
export function resultView(snapshot: SessionSnapshot): Result[] { return snapshot.results.flatMap((item) => { const raw = item.result; if (!raw?.decision) return []; const input = raw.decision; return [{ id: raw.decision.T0, decisionId: item.decisionId, status: item.status, input: { symbol: input.symbol, market: input.market === 'CN' ? 'A股' : input.market === 'HK' ? '港股' : '美股', side: input.action, executedAt: input.executedAt, price: String(input.price ?? ''), quantity: String(input.quantity ?? ''), reason: input.userReason ?? '', notes: '' }, summary: raw.decisionQuality?.reasoning ?? '暂无可靠的结构化判断。', ante: (raw.exAnteEvidence ?? []).map((e: any) => `${String(e.publishedAt ?? '').slice(0, 10)}：${e.content}`), post: (raw.exPostEvidence ?? []).map((e: any) => `${String(e.publishedAt ?? '').slice(0, 10)}：${e.content}`), raw }]; }); }
